=== JCondoriGithub/Backend/xml/ese_xsd/giornale.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/giornale" xmlns:tns="http://www.example.org/giornale" elementFormDefault="qualified">

    <element name="Giornale">
    	<complexType>
    		<sequence>
    			<element name="Articolo" minOccurs="1"
    				maxOccurs="unbounded">
    				<complexType>
    					<sequence>
    						<element name="Titolo" type="string"></element>
    						<element name="Sottotitolo" type="string"></element>
    						<element name="Intestazione"
    							type="string">
    						</element>
    						<element name="Corpo" type="string"></element>
    						<element name="Note" type="string"></element>
    					</sequence>
    					<attribute name="autore" type="string"
    						use="required">
    					</attribute>
    					<attribute name="curatore" type="string"></attribute>
    					<attribute name="data" type="date"></attribute>
    					<attribute name="edizione" type="integer"></attribute>
    				</complexType>
    			</element>
    		</sequence>
    	</complexType>
    </element>
</schema>


<!-- Creare uno Schema XML che descriva la struttura di un documento giornale, che rispetti i seguenti vincoli:
Elemento GIORNALE (ARTICOLO+)
Elemento ARTICOLO (TITOLO, SOTTOTITOLO, INTESTAZIONE, CORPO, NOTE)
Elemento TITOLO, SOTTOTITOLO, INTESTAZIONE, CORPO, NOTE sono di tipo stringa

AUTORE attributo richiesto di tipo stringa di ARTICOLO
CURATORE attributo di tipo stringa di ARTICOLO
DATA attributo di tipo data di ARTICOLO
EDIZIONE attributo di tipo intero di ARTICOLO -->

=== JCondoriGithub/Backend/xml/ese_xsd/giornale.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Giornale xmlns:tns="http://www.example.org/giornale" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/giornale giornale.xsd ">
  <tns:Articolo autore="Mauro Bisetti" data="2020-12-09" edizione="89">
    <tns:Titolo>Bastardi stilisti</tns:Titolo>
    <tns:Sottotitolo>Come mai l'hanno fatta uscire cosi?</tns:Sottotitolo>
    <tns:Intestazione>Stilisti perdono la testa</tns:Intestazione>
    <tns:Corpo>Ieri sera, al famoso evento dei grandi VIP del paese, la famosa attrice 19enne si è presentata in un abito decisamente particolare. Da mettersi le mani nei capelli insomma...</tns:Corpo>
    <tns:Note>Da verificare la punteggiatura</tns:Note>
  </tns:Articolo>
  <tns:Articolo autore="Paolo Mostri" curatore="Giancluca Meri" data="2022-02-17">
  	<tns:Titolo>Oktagon 2023</tns:Titolo>
  	<tns:Sottotitolo>A Milano ritorna la kickboxing</tns:Sottotitolo>
  	<tns:Intestazione>Evento da non perdere</tns:Intestazione>
  	<tns:Corpo>Il 30/04/2023, ritorna con furore il più grande evento della kickboxing d'Italia. Evento che inizia alle 21:00 e finisce alle 02:00 circa. Ospite speciale Mario Balotelli.</tns:Corpo>
  	<tns:Note>Da non pubblicare ancora per via di problemi legati all'evento oktagon</tns:Note>
  </tns:Articolo>
</tns:Giornale>
