=== JCondoriGithub/Backend/xml/ese_xsd/pianoDiStudio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/pianoDiStudio" xmlns:tns="http://www.example.org/pianoDiStudio" elementFormDefault="qualified">


    <element name="PianoDiStudio">
    	<complexType>
    		<sequence>
    			<element name="Studente">
    				<complexType>
    					<sequence>
    						<element name="Matricola" type="integer"></element>
    						<element name="Nome" type="string"></element>
    						<element name="Cognome" type="string"></element>
    					</sequence>
    					<attribute name="data-nascita" type="date"></attribute>
    					<attribute name="corso-laurea" type="string"></attribute>
    				</complexType>
    			</element>
    			<element name="Corsi">
    				<complexType>
    					<sequence>
    						<element name="Corso" type="tns:CorsoType"
    							minOccurs="1" maxOccurs="unbounded">
    						</element>
    					</sequence>
    				</complexType>
    			</element>
    		</sequence>
    	</complexType>
    </element>


    <complexType name="CorsoType">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="anno">
    				<simpleType>
    					<restriction base="integer">
    						<minInclusive value="1"></minInclusive>
    						<maxInclusive value="3"></maxInclusive>
    					</restriction>
    				</simpleType>
    			</attribute>
    			<attribute name="voto">
    				<simpleType>
    					<restriction base="integer">
    						<minInclusive value="18"></minInclusive>
    						<maxInclusive value="30"></maxInclusive>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>


<!-- Scrivere uno Schema XML per rappresentare le informazioni relative al piano di studio di uno studente di un certo corso di laurea triennale.
L'elemento radice deve essere pianoDiStudio. Oltre ai dati relativi allo studente (nome, cognome, matricola, data di nascita, ...) vanno rappresentati, per ogni anno di corso
frequentato dallo studente, i corsi che lo studente ha scelto di frequentare, ognuno comprendente l'eventuale voto dell'esame sostenuto positivamente.
Per distinguere i vari anni di corso utilizzare un attributo anno che puÃ² assumere solo valori interi compresi tra 1 e 3 -->

=== JCondoriGithub/Backend/xml/ese_xsd/pianoDiStudio.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:PianoDiStudio xmlns:tns="http://www.example.org/pianoDiStudio" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/pianoDiStudio pianoDiStudio.xsd ">
  <tns:Studente corso-laurea="Informatica" data-nascita="2004-11-07">
    <tns:Matricola>97852255874</tns:Matricola>
    <tns:Nome>Luca</tns:Nome>
    <tns:Cognome>Carminati</tns:Cognome>
  </tns:Studente>
  <tns:Corsi>
    <tns:Corso anno="2" voto="20">Sistemi</tns:Corso>
    <tns:Corso anno="1" voto="23">Fondamenti</tns:Corso>
    <tns:Corso anno="2" voto="27">Basi dati</tns:Corso>
    <tns:Corso anno="3" voto="26">Backend 2</tns:Corso>
    <tns:Corso anno="2" voto="29">Frontend 1</tns:Corso>
  </tns:Corsi>
</tns:PianoDiStudio>
