=== JCondoriGithub/Backend/xml/ese_dtd/letters.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Si progetti il DTD e si scriva un XML valido per un linguaggio di markup per lettere.
Ogni lettera ha un mittente, una data, un destinatario, un oggetto, una forma cortese di saluto, un corpo, una chiusura, una firma.
Il corpo della lettera ha quanto meno un paragrafo -->

<!ELEMENT letters (letter+)>
	<!ELEMENT letter (object, greeting, body, closure, signature)>
		<!ELEMENT object (#PCDATA)>
		<!ELEMENT greeting (#PCDATA)>
		<!ELEMENT body (paragraph+)>
			<!ELEMENT paragraph (#PCDATA)>
		<!ELEMENT closure (#PCDATA)>
		<!ELEMENT signature (#PCDATA)>
	
	<!ATTLIST letter
		id ID #REQUIRED
		sender CDATA #REQUIRED
		date CDATA #REQUIRED
		recipient CDATA #REQUIRED>

=== JCondoriGithub/Backend/xml/ese_dtd/letters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE letters SYSTEM "letters.dtd">

<letters>
	<letter date="19/04/2023" sender="mario.rossi@live.it" recipient="luke.ferro@hotmail.it" id="primo">
		<object>Conferma appuntamento</object>
		<greeting>Eggregio Luca</greeting>
		<body>
			<paragraph>L'appuntamento Ã¨ confermato per la data "12/05/2023"</paragraph>
		</body>
		<closure>Distinti saluti</closure>
		<signature>Mario Rossi</signature>
	</letter>
	
	<letter date="20/04/2023" sender="luke.ferro@hotmail.it" recipient="mario.rossi@live.it" id="secondo">
		<object>Avviso ricezione email</object>
		<greeting>Gentilissimo signor Mario</greeting>
		<body>
			<paragraph>Benissimo, allora ci vediamo in sede</paragraph>
			<paragraph>Confermo la ricezione dell'email</paragraph>
		</body>
		<closure>Distinti saluti</closure>
		<signature>Luca Ferro</signature>
	</letter>
</letters>
