=== JCondoriGithub/Backend/xml/ese_dtd/recipes.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT recipes (recipe+)>
	<!ELEMENT recipe (recipe_head, recipe_body, recipe_footer?, document_info)>
		<!ELEMENT recipe_head (recipe_name, recipe_author?, meal_type)>
			<!ELEMENT recipe_name (#PCDATA)>
			<!ELEMENT recipe_author (#PCDATA)>
			<!ELEMENT meal_type (#PCDATA)>
		<!ELEMENT recipe_body (ingredients, directions)>
			<!ELEMENT ingredients (ingredient+)>
			<!ELEMENT ingredient (#PCDATA)>
			<!ELEMENT directions (direction)+ >
			<!ELEMENT direction (#PCDATA)>
		<!ELEMENT recipe_footer (serving?, preparation_time?, cooking_time?)>
			<!ELEMENT serving (#PCDATA)>
			<!ELEMENT preparation_time (#PCDATA)>
			<!ELEMENT cooking_time (#PCDATA)>
		<!ELEMENT document_info (document_author, date_updated, source)>
			<!ELEMENT document_author (#PCDATA)>
			<!ELEMENT date_updated (#PCDATA)>
			<!ELEMENT source (#PCDATA)>
			
			
<!-- Una recipes deve avere almeno una ricetta, ogni ricetta deve avere: un'intestazione, un contenuto, eventualmente un pie di pagina e dell'informazione sul documento stesso.
L'intestazione ha: il nome della ricetta, eventualmente l'autore e il tipo di pasto.
Il contenuto ha: degli ingredienti e delle indicazioni. Negli ingredienti ci deve essere almeno un ingrediente e nelle indicazioni ci deve essere almeno un indicazione.
L'eventuale pie di pagina ha: eventualmente la presentazione, eventualmente il tempo di preparazione ed eventualmente il tempo di cottura.
l'informazione del documento ha: l'autore, la data di aggiornamento e la fonte -->

=== JCondoriGithub/Backend/xml/ese_dtd/recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipes SYSTEM "recipes.dtd">

<recipes>
	<recipe>
		<recipe_head>
			<recipe_name>lasagne</recipe_name>
			<recipe_author>sconoscuto</recipe_author>
			<meal_type>piatto salato</meal_type>
		</recipe_head>
		<recipe_body>
			<ingredients>
				<ingredient>carne di vitello</ingredient>
				<ingredient>sugo di pomodoro</ingredient>
				<ingredient>besciamella</ingredient>
				<ingredient>formaggio grattuggiato</ingredient>
				<ingredient>pasta sfoglia</ingredient>
			</ingredients>
			<directions>
				<direction>creare la salsa ragù</direction>
				<direction>uno strato è composto: dal ragù, dalla besciamella e dal formaggio</direction>
				<direction>fare 4/5 strati</direction>
			</directions>
		</recipe_body>
		<recipe_footer>
			<preparation_time>2 ore</preparation_time>
			<cooking_time>un ora e mezza</cooking_time>
		</recipe_footer>
		<document_info>
			<document_author>Marco Marra</document_author>
			<date_updated>02/12/2011</date_updated>
			<source>sito dell'autore</source>
		</document_info>
	</recipe>
	
	<recipe>
		<recipe_head>
			<recipe_name>pasta al sugo</recipe_name>
			<meal_type>piatto salato</meal_type>
		</recipe_head>
		<recipe_body>
			<ingredients>
				<ingredient>pasta</ingredient>
				<ingredient>sugo di pomodoro</ingredient>
			</ingredients>
			<directions>
				<direction>bollire la pasta</direction>
				<direction>cuocere il sugo e mescolarlo con la pasta</direction>
			</directions>
		</recipe_body>
		<recipe_footer>
			<serving>servire con formaggio grattuggiato</serving>
		</recipe_footer>
		<document_info>
			<document_author>Giuseppe Rossi</document_author>
			<date_updated>30/03/20</date_updated>
			<source>libro ricette</source>
		</document_info>
	</recipe>
</recipes>
